image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      sudo apt-get update &&
      sudo apt-get install -y build-essential cmake
  - command: cmake . && make

ports:
  - port: 8000
    onOpen: open-preview
